spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:accounts;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate.ddl-auto: create-drop
  cloud:
    inetutils:
      ignored-interfaces:
        - tun.*
        - eno.*
        - virbr.*
  zipkin:
    locator:
      discovery:
        enabled: true
    service:
      name: zipkin-service
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)
    log:
      json:
        enabled: true
eureka:
  instance:
    preferIpAddress: false
server:
  port: 8090
security:
  basic:
    enabled: false
management:
  security:
    enabled: false