spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate.ddl-auto: create-drop
eureka:
  instance:
    preferIpAddress: false

server:
  port: 8090

security:
  basic:
    enabled: false

management:
  security:
    enabled: false