spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - tun.*
        - eno.*
        - virbr.*
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    preferIpAddress: false
server:
  port: 8091
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
logging:
  file: customers-service.log
  level:
    org:
      hibernate: INFO
      springframework:
        web: INFO
        cloud: DEBUG
    com:
      cmc:
        api:
          controller: INFO
    root: INFO