spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - tun.*
        - eno.*
        - virbr.*
  zipkin:
    locator:
      discovery:
        enabled: true
    service:
      name: zipkin-service
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)
    log:
      json:
        enabled: true
eureka:
  instance:
    preferIpAddress: false
server:
  port: 8091
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
logging:
  file: customers-service.log
  level:
    org:
      hibernate: INFO
      springframework:
        web: INFO
        cloud: WARN
    root: INFO