spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - tun.*
        - eno.*
        - virbr.*
eureka:
  instance:
    preferIpAddress: false

server:
  port: 8092

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  file: zipkin-service.log